=== ZackAustin/Class-Programming/CS2550 - Web Development/Assignment 6 - Load XML Files/Puzzle Files/puzzleGen.dtd
<!DOCTYPE puzzle [

<!ELEMENT puzzle (node)>
<!ELEMENT node (type, value)+>
<!ELEMENT type (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ATTLIST node ID CDATA #REQUIRED>
]>

=== ZackAustin/Class-Programming/CS2550 - Web Development/Assignment 6 - Load XML Files/Puzzle Files/Hard Puzzle 1.xml
<?xml version = "1.0"?>
<!DOCTYPE puzzle SYSTEM "puzzleGen.dtd">

<puzzle>
	<node ID = "1">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "2">
		<type>predetNum</type>
		<value>2</value>
	</node>
	<node ID = "3">
		<type>predetNum</type>
		<value>3</value>
	</node>
	<node ID = "4">
		<type>predetNum</type>
		<value>7</value>
	</node>
	<node ID = "5">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "6">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "7">
		<type>predetNum</type>
		<value>1</value>
	</node>
	<node ID = "8">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "9">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "10">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "11">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "12">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "13">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "14">
		<type>predetNum</type>
		<value>8</value>
	</node>
	<node ID = "15">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "16">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "17">
		<type>predetNum</type>
		<value>2</value>
	</node>
	<node ID = "18">
		<type>predetNum</type>
		<value>5</value>
	</node>
	<node ID = "19">
		<type>predetNum</type>
		<value>5</value>
	</node>
	<node ID = "20">
		<type>predetNum</type>
		<value>7</value>
	</node>
	<node ID = "21">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "22">
		<type>predetNum</type>
		<value>9</value>
	</node>
	<node ID = "23">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "24">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "25">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "26">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "27">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "28">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "29">
		<type>predetNum</type>
		<value>5</value>
	</node>
	<node ID = "30">
		<type>predetNum</type>
		<value>4</value>
	</node>
	<node ID = "31">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "32">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "33">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "34">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "35">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "36">
		<type>predetNum</type>
		<value>2</value>
	</node>
	<node ID = "37">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "38">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "39">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "40">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "41">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "42">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "43">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "44">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "45">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "46">
		<type>predetNum</type>
		<value>6</value>
	</node>
	<node ID = "47">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "48">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "49">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "50">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "51">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "52">
		<type>predetNum</type>
		<value>4</value>
	</node>
	<node ID = "53">
		<type>predetNum</type>
		<value>8</value>
	</node>
	<node ID = "54">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "55">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "56">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "57">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "58">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "59">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "60">
		<type>predetNum</type>
		<value>4</value>
	</node>
	<node ID = "61">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "62">
		<type>predetNum</type>
		<value>1</value>
	</node>
	<node ID = "63">
		<type>predetNum</type>
		<value>6</value>
	</node>
	<node ID = "64">
		<type>predetNum</type>
		<value>1</value>
	</node>
	<node ID = "65">
		<type>predetNum</type>
		<value>8</value>
	</node>
	<node ID = "66">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "67">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "68">
		<type>predetNum</type>
		<value>6</value>
	</node>
	<node ID = "69">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "70">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "71">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "72">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "73">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "74">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "75">
		<type>predetNum</type>
		<value>2</value>
	</node>
	<node ID = "76">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "77">
		<type>userNum</type>
		<value></value>
	</node>
	<node ID = "78">
		<type>predetNum</type>
		<value>5</value>
	</node>
	<node ID = "79">
		<type>predetNum</type>
		<value>8</value>
	</node>
	<node ID = "80">
		<type>predetNum</type>
		<value>3</value>
	</node>
	<node ID = "81">
		<type>userNum</type>
		<value></value>
	</node>
</puzzle>
